Name:           ros-lunar-ar-track-alvar
Version:        0.7.0
Release:        0%{?dist}
Summary:        ROS ar_track_alvar package

Group:          Development/Libraries
License:        LGPL-2.1
URL:            http://ros.org/wiki/ar_track_alvar
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-lunar-ar-track-alvar-msgs
Requires:       ros-lunar-cv-bridge
Requires:       ros-lunar-dynamic-reconfigure
Requires:       ros-lunar-geometry-msgs
Requires:       ros-lunar-image-transport
Requires:       ros-lunar-message-runtime
Requires:       ros-lunar-pcl-conversions
Requires:       ros-lunar-pcl-ros
Requires:       ros-lunar-resource-retriever
Requires:       ros-lunar-roscpp
Requires:       ros-lunar-rospy
Requires:       ros-lunar-sensor-msgs
Requires:       ros-lunar-std-msgs
Requires:       ros-lunar-tf
Requires:       ros-lunar-tf2
Requires:       ros-lunar-visualization-msgs
Requires:       tinyxml-devel
BuildRequires:  ros-lunar-ar-track-alvar-msgs
BuildRequires:  ros-lunar-catkin
BuildRequires:  ros-lunar-cmake-modules
BuildRequires:  ros-lunar-cv-bridge
BuildRequires:  ros-lunar-dynamic-reconfigure
BuildRequires:  ros-lunar-geometry-msgs
BuildRequires:  ros-lunar-image-transport
BuildRequires:  ros-lunar-message-generation
BuildRequires:  ros-lunar-pcl-conversions
BuildRequires:  ros-lunar-pcl-ros
BuildRequires:  ros-lunar-resource-retriever
BuildRequires:  ros-lunar-rosbag
BuildRequires:  ros-lunar-roscpp
BuildRequires:  ros-lunar-rospy
BuildRequires:  ros-lunar-rostest
BuildRequires:  ros-lunar-sensor-msgs
BuildRequires:  ros-lunar-std-msgs
BuildRequires:  ros-lunar-tf
BuildRequires:  ros-lunar-tf2
BuildRequires:  ros-lunar-visualization-msgs
BuildRequires:  tinyxml-devel

%description
This package is a ROS wrapper for Alvar, an open source AR tag tracking library.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/lunar" \
        -DCMAKE_PREFIX_PATH="/opt/ros/lunar" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/lunar

%changelog
* Wed Apr 26 2017 Scott Niekum <sniekum@cs.umass.edu> - 0.7.0-0
- Autogenerated by Bloom

