Name:           ros-jade-ar-track-alvar
Version:        0.5.6
Release:        0%{?dist}
Summary:        ROS ar_track_alvar package

Group:          Development/Libraries
License:        LGPL-2.1
URL:            http://ros.org/wiki/ar_track_alvar
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-jade-ar-track-alvar-msgs
Requires:       ros-jade-cv-bridge
Requires:       ros-jade-dynamic-reconfigure
Requires:       ros-jade-geometry-msgs
Requires:       ros-jade-image-transport
Requires:       ros-jade-message-runtime
Requires:       ros-jade-pcl-conversions
Requires:       ros-jade-pcl-ros
Requires:       ros-jade-resource-retriever
Requires:       ros-jade-roscpp
Requires:       ros-jade-rospy
Requires:       ros-jade-sensor-msgs
Requires:       ros-jade-std-msgs
Requires:       ros-jade-tf
Requires:       ros-jade-tf2
Requires:       ros-jade-visualization-msgs
Requires:       tinyxml-devel
BuildRequires:  ros-jade-ar-track-alvar-msgs
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-cmake-modules
BuildRequires:  ros-jade-cv-bridge
BuildRequires:  ros-jade-dynamic-reconfigure
BuildRequires:  ros-jade-geometry-msgs
BuildRequires:  ros-jade-image-transport
BuildRequires:  ros-jade-message-generation
BuildRequires:  ros-jade-pcl-conversions
BuildRequires:  ros-jade-pcl-ros
BuildRequires:  ros-jade-resource-retriever
BuildRequires:  ros-jade-rosbag
BuildRequires:  ros-jade-roscpp
BuildRequires:  ros-jade-rospy
BuildRequires:  ros-jade-rostest
BuildRequires:  ros-jade-sensor-msgs
BuildRequires:  ros-jade-std-msgs
BuildRequires:  ros-jade-tf
BuildRequires:  ros-jade-tf2
BuildRequires:  ros-jade-visualization-msgs
BuildRequires:  tinyxml-devel

%description
This package is a ROS wrapper for Alvar, an open source AR tag tracking library.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Thu Feb 09 2017 Scott Niekum <sniekum@cs.umass.edu> - 0.5.6-0
- Autogenerated by Bloom

* Wed Feb 08 2017 Scott Niekum <sniekum@cs.umass.edu> - 0.5.5-0
- Autogenerated by Bloom

* Mon Sep 26 2016 Scott Niekum <sniekum@cs.umass.edu> - 0.5.4-0
- Autogenerated by Bloom

* Tue Feb 02 2016 Scott Niekum <sniekum@cs.umass.edu> - 0.5.3-0
- Autogenerated by Bloom

* Sat Apr 25 2015 Scott Niekum <sniekum@cs.umass.edu> - 0.5.1-0
- Autogenerated by Bloom

