Name:           ros-kinetic-ar-track-alvar-metapkg
Version:        0.7.0
Release:        2%{?dist}
Summary:        ROS ar_track_alvar_metapkg package

Group:          Development/Libraries
License:        LGPL-2.1
URL:            http://ros.org/wiki/ar_track_alvar
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-kinetic-ar-track-alvar
Requires:       ros-kinetic-ar-track-alvar-msgs
BuildRequires:  ros-kinetic-catkin

%description
Meta package for ROS ar_track_alvar related packages.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Wed Jun 14 2017 Isaac I.Y. Saito <130s@2000.jukuin.keio.ac.jp> - 0.7.0-2
- Autogenerated by Bloom

* Wed Apr 26 2017 Isaac I.Y. Saito <130s@2000.jukuin.keio.ac.jp> - 0.7.0-1
- Autogenerated by Bloom

* Wed Apr 26 2017 Isaac I.Y. Saito <130s@2000.jukuin.keio.ac.jp> - 0.7.0-0
- Autogenerated by Bloom

